# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1spUZv4q6_mggDbN-Xge1Lq43GXtvydFg
"""

import numpy as np
import matplotlib.pyplot as plt
from torch import nn
import random
import os
import torch
import torchvision
import sys
from torch.utils.tensorboard import SummaryWriter
from torchsummary import summary
from torch import autocast
import torch.nn.functional as F

import torch
from torchvision import datasets
from torchvision.transforms import ToTensor, Lambda
from torchvision import transforms

config = {
    "arch": "resnet34",
    #"dropout_rate": [0.05, 0.05], #70 40 earlier
    "seed": 2000,
    "batch_size":500,
    "num_workers": 4,
    "learning_rate": 0.0003,
    "w_decay_2": 0.8,
    "w_decay": 0.01,
    #"optim_switch_epoch": 80,
    "epochs": 100,
    "n_class":10,

    "device": torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
}

def fix_seed(seed):
    torch.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)
    np.random.seed(seed)
SEED = 2023
fix_seed(SEED)

import tensorflow as tf
img = tf.keras.preprocessing.image.load_img('/content/drive/MyDrive/Apparel_images_dataset/blue_shoes/00a9e2fb75e93c3c757b1ff908d9fcc7097f6c46.jpg')
img

print(img.size)

print(img.format)

transform =transforms.Compose([
        transforms.Resize(size = (474, 554)),
        transforms.RandomHorizontalFlip(p = 0.5),
        transforms.RandomVerticalFlip(p = 0.5),
        transforms.ColorJitter(brightness=(0.1,0.6), contrast=1,saturation=1, hue=0.4),
        transforms.ToTensor(),
        transforms.Normalize([0.485, 0.456, 0.406], [0.229, 0.224, 0.225])
    ])





